apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-keycloak
data:
  keycloak.json: |
    {
      "realm": "cdr-realm",
      "auth-server-url": "/auth",
      "ssl-required": "none",
      "resource": "cdr-frontend",
      "public-client": true,
      "confidential-port": 0,
      "redirect_uris": [
        "http://localhost/*",
        "http://localhost:80/*",
        "http://localhost",
      ]
    }
