apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 8080        # Expose on NodePort
      targetPort: 3000  # Container’s internal port
      nodePort: 30080   # External NodePort
