apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-data-pvc
spec:
  storageClassName: standard
  volumeName: users-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
