apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: catsdisownedz8/keycloak-custom:latest  # ✅ your custom Docker image with the baked-in theme
          args:
            [
              "start-dev",
              "--import-realm",
              "--http-port=8081",
              "--hostname-strict=false",
              "--hostname-strict-https=false",
              "--http-relative-path=/auth",
              "--proxy=edge"
            ]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HTTP_PORT
              value: "8081"
            - name: KEYCLOAK_THEME
              value: "cdr-pastel"
            - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
              value: "true"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: realm-volume
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: realm-volume
          configMap:
            name: cdr-realm-configmap
