apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loader
  template:
    metadata:
      labels:
        app: loader
    spec:
      containers:
        - name: loader
          image: loader-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_SERVERS
              value: "kafka:9092"
            - name: BACKEND_URL
              value: http://backend:8080
