apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;

            location / {
                proxy_pass http://frontend:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_read_timeout 300s;
                proxy_connect_timeout 300s;
                proxy_send_timeout 300s;
            }

            location /auth/ {
                proxy_pass http://keycloak.default.svc.cluster.local:8081/auth/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_read_timeout 300s;
                proxy_connect_timeout 300s;
                proxy_send_timeout 300s;
            }
        }
    }
