apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: "z"
            - name: POSTGRES_USER
              value: "z"
            - name: POSTGRES_PASSWORD
              value: "pp18"
          ports:
            - containerPort: 5432
